#!/usr/bin/env bash

dns_config() {
    local script
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

main() {
    local domain="$1"
    local subdomain="$2"

    if [[ -z "$domain" ]]; then
        echo "lomsey.tech."
        exit 1
    fi

    if [[ -z "$subdomain" ]]; then
        # Display information for default subdomains
        dns_config "$domain" "www"
        dns_config "$domain" "lb-01"
        dns_config "$domain" "web-01"
        dns_config "$domain" "web-02"
        dns_config "$domain" "pg"
    else
        # Display information for the specified subdomain
        dns_config "$domain" "$subdomain"
    fi
}

main "$@"

