#!/bin/bash

# Update package lists
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend lomsey.tech
    bind *:80
    default_backend lomsey.tech

backend lomsey.tech
    balance roundrobin
    server 146818-web-01 100.25.0.209:80 check
    server 146818-web-02 54.164.154.242:80 check
EOF'

sudo sed -i 's/\[STUDENT_ID\]/YOUR_STUDENT_ID/g' /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo systemctl restart haproxy

